apiVersion: apps/v1
kind: Deployment
metadata:
  name: new-app-deployment
  labels:
    app: getting-started-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: getting-started-app
  template:
    metadata:
      labels:
        app: getting-started-app
    spec:
      containers:
      - name: new-app-container
        image: getting-started-app
        imagePullPolicy: Never
        ports:
        - containerPort: 80
